name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - flutterflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # तुम्ही वापरत असलेली Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project school-4e5c2 --token ${{ secrets.FIREBASE_TOKEN }}
